name: Update Data

on:
  schedule:
    - cron: '*/30 * * * *' # Изменил на 15 мин, так стабильнее для GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Обновил до v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновил до v5
        with:
          python-version: '3.11'
          cache: 'pip' # Включает встроенное кэширование

      - name: Install dependencies
        run: pip install requests

      - name: Run sync
        env:
          TS_CHANNEL_ID: ${{ secrets.TS_CHANNEL_ID }}
          TS_API_KEY: ${{ secrets.TS_API_KEY }}
        run: python sync.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data_log.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update data_log.csv [skip ci]" # [skip ci] чтобы не зацикливать
            git push origin main
          fi
