name: Update Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Sync with remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main

      - name: Check file before sync
        run: |
          echo "--- ИНФОРМАЦИЯ О ФАЙЛЕ ПЕРЕД ЗАПУСКОМ ---"
          if [ -f data_log.csv ]; then
            ls -lh data_log.csv # Покажет размер (должно быть ~2.6M)
            tail -n 10 data_log.csv # Покажет последние 3 строки (проверим дату)
          else
            echo "Файл data_log.csv НЕ НАЙДЕН в репозитории!"
          fi
          echo "----------------------------------------"

      - name: Run sync
        env:
          TS_CHANNEL_ID: ${{ secrets.TS_CHANNEL_ID }}
          TS_API_KEY: ${{ secrets.TS_API_KEY }}
        run: python sync.py

      - name: Commit and Push
        run: |
          git add data_log.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update data_log.csv"
            git push origin main
          fi
